In [ ]:
# Add this at the top of your notebook
import IPython
IPython.Application.instance().kernel.do_shutdown(True)

{'status': 'ok', 'restart': True}

:

In [1]:
# importing libraries
import pandas as pd

## Loading the data
- Loading the melbourne data and then viewing it

In [2]:
# save filepath to variable for easier access
filepath = f"D:\Practice Projects\Python\Machine Learning\Kaggle Machine Learning\Melbourne Housing Problem\melb_data.csv"

melbourne_data = pd.read_csv(filepath)

# read the data and store data in DataFrame titled melbourne_data
melbourne_data.head()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra,-37.7996,144.9984,Northern Metropolitan,4019.0
1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra,-37.8079,144.9934,Northern Metropolitan,4019.0
2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra,-37.8093,144.9944,Northern Metropolitan,4019.0
3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,...,2.0,1.0,94.0,NaN,NaN,Yarra,-37.7969,144.9969,Northern Metropolitan,4019.0
4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,1.0,2.0,120.0,142.0,2014.0,Yarra,-37.8072,144.9941,Northern Metropolitan,4019.0

## Data Exploration
- Reviewing the data to understand the patterns, format, and nature of the data.

In [3]:
# print a summary of the data in the Melbourne data
melbourne_data.describe()

,Rooms,Price,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Lattitude,Longtitude,Propertycount
count,13580.000000,1.358000e+04,13580.000000,13580.000000,13580.000000,13580.000000,13518.000000,13580.000000,7130.000000,8205.000000,13580.000000,13580.000000,13580.000000
mean,2.937997,1.075684e+06,10.137776,3105.301915,2.914728,1.534242,1.610075,558.416127,151.967650,1964.684217,-37.809203,144.995216,7454.417378
std,0.955748,6.393107e+05,5.868725,90.676964,0.965921,0.691712,0.962634,3990.669241,541.014538,37.273762,0.079260,0.103916,4378.581772
min,1.000000,8.500000e+04,0.000000,3000.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1196.000000,-38.182550,144.431810,249.000000
25%,2.000000,6.500000e+05,6.100000,3044.000000,2.000000,1.000000,1.000000,177.000000,93.000000,1940.000000,-37.856822,144.929600,4380.000000
50%,3.000000,9.030000e+05,9.200000,3084.000000,3.000000,1.000000,2.000000,440.000000,126.000000,1970.000000,-37.802355,145.000100,6555.000000
75%,3.000000,1.330000e+06,13.000000,3148.000000,3.000000,2.000000,2.000000,651.000000,174.000000,1999.000000,-37.756400,145.058305,10331.000000
max,10.000000,9.000000e+06,48.100000,3977.000000,20.000000,8.000000,10.000000,433014.000000,44515.000000,2018.000000,-37.408530,145.526350,21650.000000

In [4]:
# showing the features in the dataset
melbourne_data.columns

Index(['Suburb', 'Address', 'Rooms', 'Type', 'Price', 'Method', 'SellerG',
       'Date', 'Distance', 'Postcode', 'Bedroom2', 'Bathroom', 'Car',
       'Landsize', 'BuildingArea', 'YearBuilt', 'CouncilArea', 'Lattitude',
       'Longtitude', 'Regionname', 'Propertycount'],
      dtype='object')

In [5]:
# dropna drops missing values (think of na as "not available")
melbourne_data = melbourne_data.dropna(axis=0)
print("Missing values dropped....")

Missing values dropped....

## Selecting Data for Modeling
- Using own intuition to determine the variables to be used as features in the model.
- There are two ways of selecting a subset of data:
1. **Dot notation** - we use this approach to select the "prediction target" (column we want to predict)
2. **Selecting** - with a column list, which we use to select the "features" (columns to be inputted into our model)

In [6]:
# using dot notation to pull out and define the prediction/target variable
# y variable is assigned to the prediction/target variable
y = melbourne_data.Price

In [7]:
# choosing the features to be inputted in the model
melbourne_features = ['Rooms', 'Bathroom', 'Landsize','BuildingArea', 'YearBuilt','Lattitude', 'Longtitude']

In [8]:
# X variable is assigned to the features
X = melbourne_data[melbourne_features]

In [9]:
# reviewing the data to get statistical summary
X.describe()

,Rooms,Bathroom,Landsize,BuildingArea,YearBuilt,Lattitude,Longtitude
count,6196.000000,6196.000000,6196.000000,6196.000000,6196.000000,6196.000000,6196.000000
mean,2.931407,1.576340,471.006940,141.568645,1964.081988,-37.807904,144.990201
std,0.971079,0.711362,897.449881,90.834824,38.105673,0.075850,0.099165
min,1.000000,1.000000,0.000000,0.000000,1196.000000,-38.164920,144.542370
25%,2.000000,1.000000,152.000000,91.000000,1940.000000,-37.855438,144.926198
50%,3.000000,1.000000,373.000000,124.000000,1970.000000,-37.802250,144.995800
75%,4.000000,2.000000,628.000000,170.000000,2000.000000,-37.758200,145.052700
max,8.000000,8.000000,37000.000000,3112.000000,2018.000000,-37.457090,145.526350

In [10]:
# show the x variable
X.head()

   Rooms  Bathroom  Landsize  BuildingArea  YearBuilt  Lattitude  Longtitude
1      2       1.0     156.0          79.0     1900.0   -37.8079    144.9934
2      3       2.0     134.0         150.0     1900.0   -37.8093    144.9944
4      4       1.0     120.0         142.0     2014.0   -37.8072    144.9941
6      3       2.0     245.0         210.0     1910.0   -37.8024    144.9993
7      2       1.0     256.0         107.0     1890.0   -37.8060    144.9954

## Building the Model
- We use scikit-learn library to create models which is initialized as "**sklearn**".
- The steps of building a model:
1. **Define** - What type of model will it be? A decision tree? Some other type of model? Some other parameters of the model type are specified too.
2. **Fit** - Capture patterns from provided data. This is the heart of modeling.
3. **Predict** - Just what it sounds like
4. **Evaluate** - Determine how accurate the model's predictions are.

In [11]:
# importing the sklearn library
from sklearn.tree import DecisionTreeRegressor

# Define model. Specify a number for random_state to ensure same results each run
melbourne_model = DecisionTreeRegressor(random_state=1)

# Fit model
melbourne_model.fit(X, y)

DecisionTreeRegressor(random_state=1)

In [12]:
# after fitting the model, we use it to make predictions
print("Making predictions for the following 5 houses:")
print(X.head())
print("The predictions are")
print(melbourne_model.predict(X.head()))

Making predictions for the following 5 houses:
   Rooms  Bathroom  Landsize  BuildingArea  YearBuilt  Lattitude  Longtitude
1      2       1.0     156.0          79.0     1900.0   -37.8079    144.9934
2      3       2.0     134.0         150.0     1900.0   -37.8093    144.9944
4      4       1.0     120.0         142.0     2014.0   -37.8072    144.9941
6      3       2.0     245.0         210.0     1910.0   -37.8024    144.9993
7      2       1.0     256.0         107.0     1890.0   -37.8060    144.9954
The predictions are
[1035000. 1465000. 1600000. 1876000. 1636000.]

## Model Validation
- It is important to evaluate every model that we ever build.
- The most relevant/ideal measure of model quality is predictive accuracy (will the model's predictions be close to what actually happens)
* Mistake when measuring predictive accuracy: making predictions with training data and comparing them with target values in the training data. **Problem??** - Model will always make accurate predictions and then fail on new data.
- **Best approach**, is exclude some data from model-building (training) to use the spared data (validation data) in testing model accuracy.

- Predictive accuracy measured using a single metric like **MAE (Mean Absolute Error)** as broken below:

1. **Error** - error = actual - predicted
2. **Absolute Error** - taking the absolute value of each error (convert each error to a positive number)
3. **Mean Absolute Error** - taking the average of all those absolute errors 

---
**MAE = Measure of Model Quality**

---

In [13]:
# importing the library for MAE
from sklearn.metrics import mean_absolute_error

# assigning predicted values
predicted_home_prices = melbourne_model.predict(X)

# computing MAE for the model
mean_absolute_error(y, predicted_home_prices)

434.71594577146544

## Spliting data into training and testing 
- Mistake when measuring predictive accuracy: making predictions with training data and comparing them with target values in the training data. **Problem??** - Model will always make accurate predictions and then fail on new data.
- **Best approach**, is exclude some data from model-building (training) to use the spared data (validation data) in testing model accuracy.
- To split data, we use train_test_split function in scikit-learn to breaking up the data into two pieces: training data to fit the model & testing data for model validation to calculate mean_absolute_error (MAE)

In [14]:
# importing the train_test_split function
from sklearn.model_selection import train_test_split

# split data into training and validation data, for both features and target
# The split is based on a random number generator. Supplying a numeric value to
# the random_state argument guarantees we get the same split every time we
# run this script.
train_X, val_X, train_y, val_y = train_test_split(X, y, random_state=0)

# defining the model 
melbourne_model = DecisionTreeRegressor()

# Fit the model
melbourne_model.fit(train_X, train_y)

# getting the predicted prices on the validation data
val_predictions = melbourne_model.predict(val_X)
print(mean_absolute_error(val_y, val_predictions))

258762.85409941897

- The above MAE is not good, we can improve the model in different ways, such as experimenting to find better features or different model types.

---

## Underfitting and Overfitting 
- To improve the performance of a model, we have to fine-tune it through identifying the best features to model.
- Firstly, we experiment on alternative models and see which model gives the best predictions. 
- From decision tree above, we keep splitting the data and getting deeper into leaves with fewer houses - leading to overfitting. 
- On the flips9de, if we only create shallow splits, we end up with leave with many houses - leading to underfitting. 

A. **Overfitting**: capturing spurious patterns that won't recur in the future, leading to less accurate predictions. Model is complex in this case since it works great on trained data, but fails on new data. 

B. **Underfitting**: failing to capture relevant patterns, again leading to less accurate predictions. Model is too simple that it performs poorly even on the data it was trained on. 

A good model should learn the correct rules so that it can answer and pass on new data it has not seen before. 


- Finding the sweet spot between underfitting and overfitting to improve accuracy while also finding the optimal tree depth.
- There are several ways of controlling tree depth, most clear and popular is the max_leaf_nodes function (sensible for controlling overfitting vs underfitting).

In [15]:
from sklearn.metrics import mean_absolute_error
from sklearn.tree import DecisionTreeRegressor

def get_mae(max_leaf_nodes, train_X, val_X, train_y, val_y):
    model = DecisionTreeRegressor(max_leaf_nodes=max_leaf_nodes, random_state=0)
    model.fit(train_X, train_y)
    preds_val = model.predict(val_X)
    mae = mean_absolute_error(val_y, preds_val)
    return(mae)

In [16]:
# comparing the accuracy of model built using different values for max_leaf_nodes
candidate_max_leaf_nodes = [5, 50, 500, 1000, 5000, 10000, 50000]

for max_leaf_nodes in candidate_max_leaf_nodes:
    my_mae = get_mae(max_leaf_nodes, train_X, val_X, train_y, val_y)
    print("Max leaf nodes: %d  \t\t Mean Absolute Error:  %d" %(max_leaf_nodes, my_mae))

Max leaf nodes: 5  		 Mean Absolute Error:  347380
Max leaf nodes: 50  		 Mean Absolute Error:  258171
Max leaf nodes: 500  		 Mean Absolute Error:  243495
Max leaf nodes: 1000  		 Mean Absolute Error:  247378
Max leaf nodes: 5000  		 Mean Absolute Error:  255575
Max leaf nodes: 10000  		 Mean Absolute Error:  255575
Max leaf nodes: 50000  		 Mean Absolute Error:  255575

In [18]:
# shorter version of the above loop using a dict comprehension
scores = {leaf_size: get_mae(leaf_size, train_X, val_X, train_y, val_y) for leaf_size in candidate_max_leaf_nodes}

best_tree_size = min(scores, key=scores.get)
print(f"the best tree size is: {best_tree_size} nodes")

the best tree size is: 500 nodes

---
- Of the options listed, 500 is the optimal number of leaves.
---

## Using a sophisticated model - Random Forests
- Most sophisticated models also face tension between overfitting and underfitting; having cleverer and different ideas to improve performance.

- **Random Forest**: Advanced that decision trees, it uses many trees and makes a prediction through averaging the predictions of each component trees. The model has better predictive accuracy compared to decision trees.

In [19]:
# random forest model
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error

forest_model = RandomForestRegressor(random_state=1)
forest_model.fit(train_X, train_y)
melb_preds = forest_model.predict(val_X)
print(mean_absolute_error(val_y, melb_preds))

191669.7536453626